<?php

namespace Antvr\WorkorderBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * WorkorderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WorkorderRepository extends EntityRepository
{
}
