parameters:
    #客户类型
    enterprise_type:
        1: 国有企业
        2: 集体企业
        3: 股份企业
        4: 有限公司
        5: 合伙企业
        6: 外资企业
    #客户规模
    scale:
        1: 大型（100人以上）
        2: 中型（50-100人）
        3: 小型（10-50人）
        4: 微型（10人以下）
    #客户状态
    status:
        1: 签约
        2: 掉线
    #客户级别
    grade:
        1: 高
        2: 中
        3: 低