parameters:
    menus:
        account:
            label: '工单管理'
            icon: 'fa-folder'
            children:
                workorder: { label:'新建工单', icon: 'fa-th', url: 'antvr_workorder_new' }
                contact: { label:'工单列表', icon: 'fa-user', url: 'antvr_workorder_list' }