antvr_workorder:
    resource: "@AntvrWorkorderBundle/Resources/config/routing.yml"
    prefix:   /

antvr_user:
    resource: "@AntvrUserBundle/Resources/config/routing.yml"
    prefix:   /

icsoc_ui:
    resource: "@IcsocUIBundle/Resources/config/routing.yml"
    prefix:   /
