Antvr\WorkorderBundle\Entity\Workorder:
    type: entity
    table: workorders
    repositoryClass: Antvr\WorkorderBundle\Entity\WorkorderRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    indexes:
        create_time:
            columns: [ create_time ]
        create_user:
            columns: [ create_user ]
        type_level:
            columns: [ type_level1, type_level2, type_level3 ]
    fields:
        clientName:
            type: string
            length: '50'
            column: client_name
            options:
                comment: 客户姓名
        clientPhone:
            type: string
            length: '20'
            column: client_phone
            options:
                comment: 客户联系电话
        problemSource:
            type: smallint
            column: problem_source
            options:
                comment: 问题来源(1电话/2邮件/3QQ/4微博/5微信)
                unsigned: true
                default: 0
        typeLevel1:
            type: smallint
            column: type_level1
            options:
                comment: 咨询类别1
                unsigned: true
                default: 0
        typeLevel2:
            type: smallint
            column: type_level2
            options:
                comment: 咨询类别2
                unsigned: true
                default: 0
        typeLevel3:
            type: smallint
            column: type_level3
            options:
                comment: 咨询类别3
                unsigned: true
                default: 0
        problemContent:
            type: text
            column: problem_content
            options:
                comment: 问题内容
        replyContent:
            type: text
            column: reply_content
            options:
                comment: 回复内容
        remark:
            type: text
            options:
                comment: 备注
        result:
            type: boolean
            options:
                comment: 工单结果（1已处理/0未处理）
                default: 0
                unsigned: true
        createTime:
            type: date
            column: create_time
            options:
                comment: 创建时间
        doneTime:
            type: date
            column: done_time
            options:
                comment: 处理完成时间
        createUser:
            type: integer
            column: create_user
            options:
                comment: 创建人ID
                unsigned: true
                default: 0
    lifecycleCallbacks: {  }
