icsoc_security_login:
    path:     /login
    defaults: { _controller: IcsocSecurityBundle:Security:login }

icsoc_security_login_check:
    path:    /login_check

icsoc_security_logout:
    path:    /logout
